/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as ApiWakeChatRouteImport } from './routes/api/wake-chat'
import { Route as ApiSleepChatRouteImport } from './routes/api/sleep-chat'
import { Route as ApiIaCaptureRouteImport } from './routes/api/ia-capture'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedStudioRouteImport } from './routes/_authenticated/studio'
import { Route as AuthenticatedSonhosRouteImport } from './routes/_authenticated/sonhos'
import { Route as AuthenticatedSocialRouteImport } from './routes/_authenticated/social'
import { Route as AuthenticatedRitualRouteImport } from './routes/_authenticated/ritual'
import { Route as AuthenticatedProgressoRouteImport } from './routes/_authenticated/progresso'
import { Route as AuthenticatedPlanosRouteImport } from './routes/_authenticated/planos'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedNotificacoesRouteImport } from './routes/_authenticated/notificacoes'
import { Route as AuthenticatedMissoesRouteImport } from './routes/_authenticated/missoes'
import { Route as AuthenticatedMentalRouteImport } from './routes/_authenticated/mental'
import { Route as AuthenticatedMapaRouteImport } from './routes/_authenticated/mapa'
import { Route as AuthenticatedLojaRouteImport } from './routes/_authenticated/loja'
import { Route as AuthenticatedJornadaRouteImport } from './routes/_authenticated/jornada'
import { Route as AuthenticatedIaRouteImport } from './routes/_authenticated/ia'
import { Route as AuthenticatedHabitosRouteImport } from './routes/_authenticated/habitos'
import { Route as AuthenticatedDormirRouteImport } from './routes/_authenticated/dormir'
import { Route as AuthenticatedDespertarRouteImport } from './routes/_authenticated/despertar'
import { Route as AuthenticatedDesafiosRouteImport } from './routes/_authenticated/desafios'
import { Route as AuthenticatedCristaisRouteImport } from './routes/_authenticated/cristais'
import { Route as AuthenticatedConquistasRouteImport } from './routes/_authenticated/conquistas'
import { Route as AuthenticatedClasseRouteImport } from './routes/_authenticated/classe'
import { Route as AuthenticatedCalendarioRouteImport } from './routes/_authenticated/calendario'
import { Route as AuthenticatedAlarmeRouteImport } from './routes/_authenticated/alarme'
import { Route as AuthenticatedAreaOrientadorRouteImport } from './routes/_authenticated/area.orientador'
import { Route as AuthenticatedAreaSlugRouteImport } from './routes/_authenticated/area.$slug'
import { Route as ApiPublicHooksGenerateNudgesRouteImport } from './routes/api/public/hooks/generate-nudges'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWakeChatRoute = ApiWakeChatRouteImport.update({
  id: '/api/wake-chat',
  path: '/api/wake-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSleepChatRoute = ApiSleepChatRouteImport.update({
  id: '/api/sleep-chat',
  path: '/api/sleep-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIaCaptureRoute = ApiIaCaptureRouteImport.update({
  id: '/api/ia-capture',
  path: '/api/ia-capture',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStudioRoute = AuthenticatedStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSonhosRoute = AuthenticatedSonhosRouteImport.update({
  id: '/sonhos',
  path: '/sonhos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSocialRoute = AuthenticatedSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRitualRoute = AuthenticatedRitualRouteImport.update({
  id: '/ritual',
  path: '/ritual',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProgressoRoute = AuthenticatedProgressoRouteImport.update({
  id: '/progresso',
  path: '/progresso',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanosRoute = AuthenticatedPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificacoesRoute =
  AuthenticatedNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMissoesRoute = AuthenticatedMissoesRouteImport.update({
  id: '/missoes',
  path: '/missoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMentalRoute = AuthenticatedMentalRouteImport.update({
  id: '/mental',
  path: '/mental',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMapaRoute = AuthenticatedMapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLojaRoute = AuthenticatedLojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJornadaRoute = AuthenticatedJornadaRouteImport.update({
  id: '/jornada',
  path: '/jornada',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIaRoute = AuthenticatedIaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHabitosRoute = AuthenticatedHabitosRouteImport.update({
  id: '/habitos',
  path: '/habitos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDormirRoute = AuthenticatedDormirRouteImport.update({
  id: '/dormir',
  path: '/dormir',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDespertarRoute = AuthenticatedDespertarRouteImport.update({
  id: '/despertar',
  path: '/despertar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDesafiosRoute = AuthenticatedDesafiosRouteImport.update({
  id: '/desafios',
  path: '/desafios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCristaisRoute = AuthenticatedCristaisRouteImport.update({
  id: '/cristais',
  path: '/cristais',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConquistasRoute = AuthenticatedConquistasRouteImport.update({
  id: '/conquistas',
  path: '/conquistas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClasseRoute = AuthenticatedClasseRouteImport.update({
  id: '/classe',
  path: '/classe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarioRoute = AuthenticatedCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlarmeRoute = AuthenticatedAlarmeRouteImport.update({
  id: '/alarme',
  path: '/alarme',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAreaOrientadorRoute =
  AuthenticatedAreaOrientadorRouteImport.update({
    id: '/area/orientador',
    path: '/area/orientador',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAreaSlugRoute = AuthenticatedAreaSlugRouteImport.update({
  id: '/area/$slug',
  path: '/area/$slug',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicHooksGenerateNudgesRoute =
  ApiPublicHooksGenerateNudgesRouteImport.update({
    id: '/api/public/hooks/generate-nudges',
    path: '/api/public/hooks/generate-nudges',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/alarme': typeof AuthenticatedAlarmeRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/classe': typeof AuthenticatedClasseRoute
  '/conquistas': typeof AuthenticatedConquistasRoute
  '/cristais': typeof AuthenticatedCristaisRoute
  '/desafios': typeof AuthenticatedDesafiosRoute
  '/despertar': typeof AuthenticatedDespertarRoute
  '/dormir': typeof AuthenticatedDormirRoute
  '/habitos': typeof AuthenticatedHabitosRoute
  '/ia': typeof AuthenticatedIaRoute
  '/jornada': typeof AuthenticatedJornadaRoute
  '/loja': typeof AuthenticatedLojaRoute
  '/mapa': typeof AuthenticatedMapaRoute
  '/mental': typeof AuthenticatedMentalRoute
  '/missoes': typeof AuthenticatedMissoesRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/planos': typeof AuthenticatedPlanosRoute
  '/progresso': typeof AuthenticatedProgressoRoute
  '/ritual': typeof AuthenticatedRitualRoute
  '/social': typeof AuthenticatedSocialRoute
  '/sonhos': typeof AuthenticatedSonhosRoute
  '/studio': typeof AuthenticatedStudioRoute
  '/api/chat': typeof ApiChatRoute
  '/api/ia-capture': typeof ApiIaCaptureRoute
  '/api/sleep-chat': typeof ApiSleepChatRoute
  '/api/wake-chat': typeof ApiWakeChatRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/area/$slug': typeof AuthenticatedAreaSlugRoute
  '/area/orientador': typeof AuthenticatedAreaOrientadorRoute
  '/api/public/hooks/generate-nudges': typeof ApiPublicHooksGenerateNudgesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/alarme': typeof AuthenticatedAlarmeRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/classe': typeof AuthenticatedClasseRoute
  '/conquistas': typeof AuthenticatedConquistasRoute
  '/cristais': typeof AuthenticatedCristaisRoute
  '/desafios': typeof AuthenticatedDesafiosRoute
  '/despertar': typeof AuthenticatedDespertarRoute
  '/dormir': typeof AuthenticatedDormirRoute
  '/habitos': typeof AuthenticatedHabitosRoute
  '/ia': typeof AuthenticatedIaRoute
  '/jornada': typeof AuthenticatedJornadaRoute
  '/loja': typeof AuthenticatedLojaRoute
  '/mapa': typeof AuthenticatedMapaRoute
  '/mental': typeof AuthenticatedMentalRoute
  '/missoes': typeof AuthenticatedMissoesRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/planos': typeof AuthenticatedPlanosRoute
  '/progresso': typeof AuthenticatedProgressoRoute
  '/ritual': typeof AuthenticatedRitualRoute
  '/social': typeof AuthenticatedSocialRoute
  '/sonhos': typeof AuthenticatedSonhosRoute
  '/studio': typeof AuthenticatedStudioRoute
  '/api/chat': typeof ApiChatRoute
  '/api/ia-capture': typeof ApiIaCaptureRoute
  '/api/sleep-chat': typeof ApiSleepChatRoute
  '/api/wake-chat': typeof ApiWakeChatRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/area/$slug': typeof AuthenticatedAreaSlugRoute
  '/area/orientador': typeof AuthenticatedAreaOrientadorRoute
  '/api/public/hooks/generate-nudges': typeof ApiPublicHooksGenerateNudgesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/alarme': typeof AuthenticatedAlarmeRoute
  '/_authenticated/calendario': typeof AuthenticatedCalendarioRoute
  '/_authenticated/classe': typeof AuthenticatedClasseRoute
  '/_authenticated/conquistas': typeof AuthenticatedConquistasRoute
  '/_authenticated/cristais': typeof AuthenticatedCristaisRoute
  '/_authenticated/desafios': typeof AuthenticatedDesafiosRoute
  '/_authenticated/despertar': typeof AuthenticatedDespertarRoute
  '/_authenticated/dormir': typeof AuthenticatedDormirRoute
  '/_authenticated/habitos': typeof AuthenticatedHabitosRoute
  '/_authenticated/ia': typeof AuthenticatedIaRoute
  '/_authenticated/jornada': typeof AuthenticatedJornadaRoute
  '/_authenticated/loja': typeof AuthenticatedLojaRoute
  '/_authenticated/mapa': typeof AuthenticatedMapaRoute
  '/_authenticated/mental': typeof AuthenticatedMentalRoute
  '/_authenticated/missoes': typeof AuthenticatedMissoesRoute
  '/_authenticated/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/planos': typeof AuthenticatedPlanosRoute
  '/_authenticated/progresso': typeof AuthenticatedProgressoRoute
  '/_authenticated/ritual': typeof AuthenticatedRitualRoute
  '/_authenticated/social': typeof AuthenticatedSocialRoute
  '/_authenticated/sonhos': typeof AuthenticatedSonhosRoute
  '/_authenticated/studio': typeof AuthenticatedStudioRoute
  '/api/chat': typeof ApiChatRoute
  '/api/ia-capture': typeof ApiIaCaptureRoute
  '/api/sleep-chat': typeof ApiSleepChatRoute
  '/api/wake-chat': typeof ApiWakeChatRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/_authenticated/area/$slug': typeof AuthenticatedAreaSlugRoute
  '/_authenticated/area/orientador': typeof AuthenticatedAreaOrientadorRoute
  '/api/public/hooks/generate-nudges': typeof ApiPublicHooksGenerateNudgesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/alarme'
    | '/calendario'
    | '/classe'
    | '/conquistas'
    | '/cristais'
    | '/desafios'
    | '/despertar'
    | '/dormir'
    | '/habitos'
    | '/ia'
    | '/jornada'
    | '/loja'
    | '/mapa'
    | '/mental'
    | '/missoes'
    | '/notificacoes'
    | '/onboarding'
    | '/painel'
    | '/perfil'
    | '/planos'
    | '/progresso'
    | '/ritual'
    | '/social'
    | '/sonhos'
    | '/studio'
    | '/api/chat'
    | '/api/ia-capture'
    | '/api/sleep-chat'
    | '/api/wake-chat'
    | '/checkout/return'
    | '/area/$slug'
    | '/area/orientador'
    | '/api/public/hooks/generate-nudges'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/alarme'
    | '/calendario'
    | '/classe'
    | '/conquistas'
    | '/cristais'
    | '/desafios'
    | '/despertar'
    | '/dormir'
    | '/habitos'
    | '/ia'
    | '/jornada'
    | '/loja'
    | '/mapa'
    | '/mental'
    | '/missoes'
    | '/notificacoes'
    | '/onboarding'
    | '/painel'
    | '/perfil'
    | '/planos'
    | '/progresso'
    | '/ritual'
    | '/social'
    | '/sonhos'
    | '/studio'
    | '/api/chat'
    | '/api/ia-capture'
    | '/api/sleep-chat'
    | '/api/wake-chat'
    | '/checkout/return'
    | '/area/$slug'
    | '/area/orientador'
    | '/api/public/hooks/generate-nudges'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/alarme'
    | '/_authenticated/calendario'
    | '/_authenticated/classe'
    | '/_authenticated/conquistas'
    | '/_authenticated/cristais'
    | '/_authenticated/desafios'
    | '/_authenticated/despertar'
    | '/_authenticated/dormir'
    | '/_authenticated/habitos'
    | '/_authenticated/ia'
    | '/_authenticated/jornada'
    | '/_authenticated/loja'
    | '/_authenticated/mapa'
    | '/_authenticated/mental'
    | '/_authenticated/missoes'
    | '/_authenticated/notificacoes'
    | '/_authenticated/onboarding'
    | '/_authenticated/painel'
    | '/_authenticated/perfil'
    | '/_authenticated/planos'
    | '/_authenticated/progresso'
    | '/_authenticated/ritual'
    | '/_authenticated/social'
    | '/_authenticated/sonhos'
    | '/_authenticated/studio'
    | '/api/chat'
    | '/api/ia-capture'
    | '/api/sleep-chat'
    | '/api/wake-chat'
    | '/checkout/return'
    | '/_authenticated/area/$slug'
    | '/_authenticated/area/orientador'
    | '/api/public/hooks/generate-nudges'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiIaCaptureRoute: typeof ApiIaCaptureRoute
  ApiSleepChatRoute: typeof ApiSleepChatRoute
  ApiWakeChatRoute: typeof ApiWakeChatRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  ApiPublicHooksGenerateNudgesRoute: typeof ApiPublicHooksGenerateNudgesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wake-chat': {
      id: '/api/wake-chat'
      path: '/api/wake-chat'
      fullPath: '/api/wake-chat'
      preLoaderRoute: typeof ApiWakeChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sleep-chat': {
      id: '/api/sleep-chat'
      path: '/api/sleep-chat'
      fullPath: '/api/sleep-chat'
      preLoaderRoute: typeof ApiSleepChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ia-capture': {
      id: '/api/ia-capture'
      path: '/api/ia-capture'
      fullPath: '/api/ia-capture'
      preLoaderRoute: typeof ApiIaCaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/studio': {
      id: '/_authenticated/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof AuthenticatedStudioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sonhos': {
      id: '/_authenticated/sonhos'
      path: '/sonhos'
      fullPath: '/sonhos'
      preLoaderRoute: typeof AuthenticatedSonhosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/social': {
      id: '/_authenticated/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof AuthenticatedSocialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ritual': {
      id: '/_authenticated/ritual'
      path: '/ritual'
      fullPath: '/ritual'
      preLoaderRoute: typeof AuthenticatedRitualRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/progresso': {
      id: '/_authenticated/progresso'
      path: '/progresso'
      fullPath: '/progresso'
      preLoaderRoute: typeof AuthenticatedProgressoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planos': {
      id: '/_authenticated/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof AuthenticatedPlanosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notificacoes': {
      id: '/_authenticated/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof AuthenticatedNotificacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/missoes': {
      id: '/_authenticated/missoes'
      path: '/missoes'
      fullPath: '/missoes'
      preLoaderRoute: typeof AuthenticatedMissoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mental': {
      id: '/_authenticated/mental'
      path: '/mental'
      fullPath: '/mental'
      preLoaderRoute: typeof AuthenticatedMentalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mapa': {
      id: '/_authenticated/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof AuthenticatedMapaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/loja': {
      id: '/_authenticated/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof AuthenticatedLojaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jornada': {
      id: '/_authenticated/jornada'
      path: '/jornada'
      fullPath: '/jornada'
      preLoaderRoute: typeof AuthenticatedJornadaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ia': {
      id: '/_authenticated/ia'
      path: '/ia'
      fullPath: '/ia'
      preLoaderRoute: typeof AuthenticatedIaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/habitos': {
      id: '/_authenticated/habitos'
      path: '/habitos'
      fullPath: '/habitos'
      preLoaderRoute: typeof AuthenticatedHabitosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dormir': {
      id: '/_authenticated/dormir'
      path: '/dormir'
      fullPath: '/dormir'
      preLoaderRoute: typeof AuthenticatedDormirRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/despertar': {
      id: '/_authenticated/despertar'
      path: '/despertar'
      fullPath: '/despertar'
      preLoaderRoute: typeof AuthenticatedDespertarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/desafios': {
      id: '/_authenticated/desafios'
      path: '/desafios'
      fullPath: '/desafios'
      preLoaderRoute: typeof AuthenticatedDesafiosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cristais': {
      id: '/_authenticated/cristais'
      path: '/cristais'
      fullPath: '/cristais'
      preLoaderRoute: typeof AuthenticatedCristaisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conquistas': {
      id: '/_authenticated/conquistas'
      path: '/conquistas'
      fullPath: '/conquistas'
      preLoaderRoute: typeof AuthenticatedConquistasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/classe': {
      id: '/_authenticated/classe'
      path: '/classe'
      fullPath: '/classe'
      preLoaderRoute: typeof AuthenticatedClasseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendario': {
      id: '/_authenticated/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AuthenticatedCalendarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alarme': {
      id: '/_authenticated/alarme'
      path: '/alarme'
      fullPath: '/alarme'
      preLoaderRoute: typeof AuthenticatedAlarmeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/area/orientador': {
      id: '/_authenticated/area/orientador'
      path: '/area/orientador'
      fullPath: '/area/orientador'
      preLoaderRoute: typeof AuthenticatedAreaOrientadorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/area/$slug': {
      id: '/_authenticated/area/$slug'
      path: '/area/$slug'
      fullPath: '/area/$slug'
      preLoaderRoute: typeof AuthenticatedAreaSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/generate-nudges': {
      id: '/api/public/hooks/generate-nudges'
      path: '/api/public/hooks/generate-nudges'
      fullPath: '/api/public/hooks/generate-nudges'
      preLoaderRoute: typeof ApiPublicHooksGenerateNudgesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAlarmeRoute: typeof AuthenticatedAlarmeRoute
  AuthenticatedCalendarioRoute: typeof AuthenticatedCalendarioRoute
  AuthenticatedClasseRoute: typeof AuthenticatedClasseRoute
  AuthenticatedConquistasRoute: typeof AuthenticatedConquistasRoute
  AuthenticatedCristaisRoute: typeof AuthenticatedCristaisRoute
  AuthenticatedDesafiosRoute: typeof AuthenticatedDesafiosRoute
  AuthenticatedDespertarRoute: typeof AuthenticatedDespertarRoute
  AuthenticatedDormirRoute: typeof AuthenticatedDormirRoute
  AuthenticatedHabitosRoute: typeof AuthenticatedHabitosRoute
  AuthenticatedIaRoute: typeof AuthenticatedIaRoute
  AuthenticatedJornadaRoute: typeof AuthenticatedJornadaRoute
  AuthenticatedLojaRoute: typeof AuthenticatedLojaRoute
  AuthenticatedMapaRoute: typeof AuthenticatedMapaRoute
  AuthenticatedMentalRoute: typeof AuthenticatedMentalRoute
  AuthenticatedMissoesRoute: typeof AuthenticatedMissoesRoute
  AuthenticatedNotificacoesRoute: typeof AuthenticatedNotificacoesRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedPlanosRoute: typeof AuthenticatedPlanosRoute
  AuthenticatedProgressoRoute: typeof AuthenticatedProgressoRoute
  AuthenticatedRitualRoute: typeof AuthenticatedRitualRoute
  AuthenticatedSocialRoute: typeof AuthenticatedSocialRoute
  AuthenticatedSonhosRoute: typeof AuthenticatedSonhosRoute
  AuthenticatedStudioRoute: typeof AuthenticatedStudioRoute
  AuthenticatedAreaSlugRoute: typeof AuthenticatedAreaSlugRoute
  AuthenticatedAreaOrientadorRoute: typeof AuthenticatedAreaOrientadorRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAlarmeRoute: AuthenticatedAlarmeRoute,
  AuthenticatedCalendarioRoute: AuthenticatedCalendarioRoute,
  AuthenticatedClasseRoute: AuthenticatedClasseRoute,
  AuthenticatedConquistasRoute: AuthenticatedConquistasRoute,
  AuthenticatedCristaisRoute: AuthenticatedCristaisRoute,
  AuthenticatedDesafiosRoute: AuthenticatedDesafiosRoute,
  AuthenticatedDespertarRoute: AuthenticatedDespertarRoute,
  AuthenticatedDormirRoute: AuthenticatedDormirRoute,
  AuthenticatedHabitosRoute: AuthenticatedHabitosRoute,
  AuthenticatedIaRoute: AuthenticatedIaRoute,
  AuthenticatedJornadaRoute: AuthenticatedJornadaRoute,
  AuthenticatedLojaRoute: AuthenticatedLojaRoute,
  AuthenticatedMapaRoute: AuthenticatedMapaRoute,
  AuthenticatedMentalRoute: AuthenticatedMentalRoute,
  AuthenticatedMissoesRoute: AuthenticatedMissoesRoute,
  AuthenticatedNotificacoesRoute: AuthenticatedNotificacoesRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedPlanosRoute: AuthenticatedPlanosRoute,
  AuthenticatedProgressoRoute: AuthenticatedProgressoRoute,
  AuthenticatedRitualRoute: AuthenticatedRitualRoute,
  AuthenticatedSocialRoute: AuthenticatedSocialRoute,
  AuthenticatedSonhosRoute: AuthenticatedSonhosRoute,
  AuthenticatedStudioRoute: AuthenticatedStudioRoute,
  AuthenticatedAreaSlugRoute: AuthenticatedAreaSlugRoute,
  AuthenticatedAreaOrientadorRoute: AuthenticatedAreaOrientadorRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiChatRoute: ApiChatRoute,
  ApiIaCaptureRoute: ApiIaCaptureRoute,
  ApiSleepChatRoute: ApiSleepChatRoute,
  ApiWakeChatRoute: ApiWakeChatRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  ApiPublicHooksGenerateNudgesRoute: ApiPublicHooksGenerateNudgesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
