/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedSocialRouteImport } from './routes/_authenticated/social'
import { Route as AuthenticatedRitualRouteImport } from './routes/_authenticated/ritual'
import { Route as AuthenticatedProgressoRouteImport } from './routes/_authenticated/progresso'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedMapaRouteImport } from './routes/_authenticated/mapa'
import { Route as AuthenticatedLojaRouteImport } from './routes/_authenticated/loja'
import { Route as AuthenticatedHabitosRouteImport } from './routes/_authenticated/habitos'
import { Route as AuthenticatedConquistasRouteImport } from './routes/_authenticated/conquistas'
import { Route as AuthenticatedClasseRouteImport } from './routes/_authenticated/classe'
import { Route as AuthenticatedCalendarioRouteImport } from './routes/_authenticated/calendario'
import { Route as AuthenticatedAreaOrientadorRouteImport } from './routes/_authenticated/area.orientador'
import { Route as AuthenticatedAreaSlugRouteImport } from './routes/_authenticated/area.$slug'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSocialRoute = AuthenticatedSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRitualRoute = AuthenticatedRitualRouteImport.update({
  id: '/ritual',
  path: '/ritual',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProgressoRoute = AuthenticatedProgressoRouteImport.update({
  id: '/progresso',
  path: '/progresso',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMapaRoute = AuthenticatedMapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLojaRoute = AuthenticatedLojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHabitosRoute = AuthenticatedHabitosRouteImport.update({
  id: '/habitos',
  path: '/habitos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConquistasRoute = AuthenticatedConquistasRouteImport.update({
  id: '/conquistas',
  path: '/conquistas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClasseRoute = AuthenticatedClasseRouteImport.update({
  id: '/classe',
  path: '/classe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarioRoute = AuthenticatedCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAreaOrientadorRoute =
  AuthenticatedAreaOrientadorRouteImport.update({
    id: '/area/orientador',
    path: '/area/orientador',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAreaSlugRoute = AuthenticatedAreaSlugRouteImport.update({
  id: '/area/$slug',
  path: '/area/$slug',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/classe': typeof AuthenticatedClasseRoute
  '/conquistas': typeof AuthenticatedConquistasRoute
  '/habitos': typeof AuthenticatedHabitosRoute
  '/loja': typeof AuthenticatedLojaRoute
  '/mapa': typeof AuthenticatedMapaRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/progresso': typeof AuthenticatedProgressoRoute
  '/ritual': typeof AuthenticatedRitualRoute
  '/social': typeof AuthenticatedSocialRoute
  '/api/chat': typeof ApiChatRoute
  '/area/$slug': typeof AuthenticatedAreaSlugRoute
  '/area/orientador': typeof AuthenticatedAreaOrientadorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/classe': typeof AuthenticatedClasseRoute
  '/conquistas': typeof AuthenticatedConquistasRoute
  '/habitos': typeof AuthenticatedHabitosRoute
  '/loja': typeof AuthenticatedLojaRoute
  '/mapa': typeof AuthenticatedMapaRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/progresso': typeof AuthenticatedProgressoRoute
  '/ritual': typeof AuthenticatedRitualRoute
  '/social': typeof AuthenticatedSocialRoute
  '/api/chat': typeof ApiChatRoute
  '/area/$slug': typeof AuthenticatedAreaSlugRoute
  '/area/orientador': typeof AuthenticatedAreaOrientadorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/calendario': typeof AuthenticatedCalendarioRoute
  '/_authenticated/classe': typeof AuthenticatedClasseRoute
  '/_authenticated/conquistas': typeof AuthenticatedConquistasRoute
  '/_authenticated/habitos': typeof AuthenticatedHabitosRoute
  '/_authenticated/loja': typeof AuthenticatedLojaRoute
  '/_authenticated/mapa': typeof AuthenticatedMapaRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/progresso': typeof AuthenticatedProgressoRoute
  '/_authenticated/ritual': typeof AuthenticatedRitualRoute
  '/_authenticated/social': typeof AuthenticatedSocialRoute
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/area/$slug': typeof AuthenticatedAreaSlugRoute
  '/_authenticated/area/orientador': typeof AuthenticatedAreaOrientadorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calendario'
    | '/classe'
    | '/conquistas'
    | '/habitos'
    | '/loja'
    | '/mapa'
    | '/onboarding'
    | '/painel'
    | '/perfil'
    | '/progresso'
    | '/ritual'
    | '/social'
    | '/api/chat'
    | '/area/$slug'
    | '/area/orientador'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/calendario'
    | '/classe'
    | '/conquistas'
    | '/habitos'
    | '/loja'
    | '/mapa'
    | '/onboarding'
    | '/painel'
    | '/perfil'
    | '/progresso'
    | '/ritual'
    | '/social'
    | '/api/chat'
    | '/area/$slug'
    | '/area/orientador'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/calendario'
    | '/_authenticated/classe'
    | '/_authenticated/conquistas'
    | '/_authenticated/habitos'
    | '/_authenticated/loja'
    | '/_authenticated/mapa'
    | '/_authenticated/onboarding'
    | '/_authenticated/painel'
    | '/_authenticated/perfil'
    | '/_authenticated/progresso'
    | '/_authenticated/ritual'
    | '/_authenticated/social'
    | '/api/chat'
    | '/_authenticated/area/$slug'
    | '/_authenticated/area/orientador'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/social': {
      id: '/_authenticated/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof AuthenticatedSocialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ritual': {
      id: '/_authenticated/ritual'
      path: '/ritual'
      fullPath: '/ritual'
      preLoaderRoute: typeof AuthenticatedRitualRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/progresso': {
      id: '/_authenticated/progresso'
      path: '/progresso'
      fullPath: '/progresso'
      preLoaderRoute: typeof AuthenticatedProgressoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mapa': {
      id: '/_authenticated/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof AuthenticatedMapaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/loja': {
      id: '/_authenticated/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof AuthenticatedLojaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/habitos': {
      id: '/_authenticated/habitos'
      path: '/habitos'
      fullPath: '/habitos'
      preLoaderRoute: typeof AuthenticatedHabitosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conquistas': {
      id: '/_authenticated/conquistas'
      path: '/conquistas'
      fullPath: '/conquistas'
      preLoaderRoute: typeof AuthenticatedConquistasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/classe': {
      id: '/_authenticated/classe'
      path: '/classe'
      fullPath: '/classe'
      preLoaderRoute: typeof AuthenticatedClasseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendario': {
      id: '/_authenticated/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AuthenticatedCalendarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/area/orientador': {
      id: '/_authenticated/area/orientador'
      path: '/area/orientador'
      fullPath: '/area/orientador'
      preLoaderRoute: typeof AuthenticatedAreaOrientadorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/area/$slug': {
      id: '/_authenticated/area/$slug'
      path: '/area/$slug'
      fullPath: '/area/$slug'
      preLoaderRoute: typeof AuthenticatedAreaSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCalendarioRoute: typeof AuthenticatedCalendarioRoute
  AuthenticatedClasseRoute: typeof AuthenticatedClasseRoute
  AuthenticatedConquistasRoute: typeof AuthenticatedConquistasRoute
  AuthenticatedHabitosRoute: typeof AuthenticatedHabitosRoute
  AuthenticatedLojaRoute: typeof AuthenticatedLojaRoute
  AuthenticatedMapaRoute: typeof AuthenticatedMapaRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedProgressoRoute: typeof AuthenticatedProgressoRoute
  AuthenticatedRitualRoute: typeof AuthenticatedRitualRoute
  AuthenticatedSocialRoute: typeof AuthenticatedSocialRoute
  AuthenticatedAreaSlugRoute: typeof AuthenticatedAreaSlugRoute
  AuthenticatedAreaOrientadorRoute: typeof AuthenticatedAreaOrientadorRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCalendarioRoute: AuthenticatedCalendarioRoute,
  AuthenticatedClasseRoute: AuthenticatedClasseRoute,
  AuthenticatedConquistasRoute: AuthenticatedConquistasRoute,
  AuthenticatedHabitosRoute: AuthenticatedHabitosRoute,
  AuthenticatedLojaRoute: AuthenticatedLojaRoute,
  AuthenticatedMapaRoute: AuthenticatedMapaRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedProgressoRoute: AuthenticatedProgressoRoute,
  AuthenticatedRitualRoute: AuthenticatedRitualRoute,
  AuthenticatedSocialRoute: AuthenticatedSocialRoute,
  AuthenticatedAreaSlugRoute: AuthenticatedAreaSlugRoute,
  AuthenticatedAreaOrientadorRoute: AuthenticatedAreaOrientadorRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
