ALTER TABLE public.notification_prefs
  ADD COLUMN IF NOT EXISTS quiet_start SMALLINT NOT NULL DEFAULT 23,
  ADD COLUMN IF NOT EXISTS quiet_end SMALLINT NOT NULL DEFAULT 7,
  ADD COLUMN IF NOT EXISTS allow_mission BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS allow_ritual BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS allow_streak BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS allow_orientador BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS allow_social BOOLEAN NOT NULL DEFAULT true;